### ISSUE TITLE
运行train.py出现Corrupted image for 5372问题，求各位大神指教

### ISSUE THREAD

**Issue by ShangLe0607** [AstarLight/Lets_OCR#73]
你好，我运行train.py出现一下问题，请问是怎么回事啊
Corrupted image for 5362
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 128326) exited unexpectedly
Corrupted image for 5181
Corrupted image for 6898
Corrupted image for 1689
Corrupted image for 5364
Corrupted image for 5183
Corrupted image for 6900
Corrupted image for 1691
Corrupted image for 5366
Corrupted image for 5185
Corrupted image for 6902
Corrupted image for 1693
Corrupted image for 5368
Corrupted image for 5187
Corrupted image for 6904
Corrupted image for 1695
Corrupted image for 5370
Corrupted image for 5189
Corrupted image for 6906
Corrupted image for 1697
Corrupted image for 5372
[root@localhost crnn]#

**Comment by chenshihao123456** [comment]
如何解决的？

**Comment by oweiii** [comment]
请问该怎么解决
