### ISSUE TITLE
提供标签（图像路径 中文字符）

### ISSUE THREAD

**Issue by zchoi** [AstarLight/Lets_OCR#82]
链接：https://pan.baidu.com/s/16Zpjx_lT-o1inV1mnboBbg 
提取码：kj2p

文件不小心被我删除，链接🔗失效了  补一个：
链接：https://pan.baidu.com/s/145Y_JUqrJ93AuYHPTf_L9g 
提取码：m4c4

**Comment by lironghua318** [comment]
感谢分享，作者代码和提供的数据标注不对应

**Comment by ChuoQi** [comment]
连接失效了，可以再分享一下吗？感谢！ @zchoi

**Comment by rsqai** [comment]
赞一个，亲测有效的数据集

**Comment by Bonnie-gift** [comment]
等会试试
