### ISSUE TITLE
Got a error of " can not import name 'gen_geo_map' when running train.py for east part 

### ISSUE THREAD

**Issue by lmw0320** [AstarLight/Lets_OCR#92]
跑east训练代码的时候，遇到一个错误： cannot import name 'gen_geo_map‘,  我查看了相关的文件夹，里面的确没有这个gen_geo_map.py文件，倒是有不少文件名称相同的其他文件，如：gen_geo_map.so， gen_geo_map.c，gen_geo_map.pyx。。。这个怎么解决？？

**Comment by HiIcy** [comment]
这个问题是怎么解决的
