### ISSUE TITLE
infer  w160_bs64_model下的模型，识别结果都是错误的

### ISSUE THREAD

**Issue by hwangyl** [AstarLight/Lets_OCR#93]
![2020-09-07 19-45-44屏幕截图](https://user-images.githubusercontent.com/27655512/92384669-107dbc80-f143-11ea-920e-43668bfd46a9.png)

**Comment by Yaoxingtian** [comment]
我导入这个模型infer的时候 报错了：    print('loading pretrained model from {0}'.format(crnn_model_path))
是模型有问题吗

**Comment by junewgl** [comment]
我也觉得是错的
